### ISSUE TITLE
The method splitMessage never writes to 20% file

### ISSUE THREAD

**Issue by kbml** [shreya-bhatnagar/Sms-Classification#2]
https://github.com/shreya-bhatnagar/Sms-Classification/blob/f055053c94be71313c74a6a57bde34cafa1841ba/src/Input/SmsDistribution.java#L65

**Comment by shreya-bhatnagar** [comment]
I have committed new changes yesterday night, Now check if the new changes is visible in this file.
https://github.com/shreya-bhatnagar/Sms-Classification/blob/master/src/Input/SmsDistribution.java

**Comment by kbml** [comment]
OK.
